import { openDB, type DBSchema, type IDBPDatabase } from "idb";

import { OCTI_WEB_CHANNEL } from "../version";

/**
 * Mirrors the per-device subset of {@link eu.darken.octi.syncs.octiserver.core.OctiServer.Credentials}
 * plus the locally-generated {@code ownDeviceId} that the Android app keeps in its sync settings.
 *
 * One record = one linked account. v1 only ever holds a single record at a time, but the schema
 * (keyed by accountId) is multi-account-ready so we don't have to migrate later.
 */
export interface CredentialRecord {
  /** Server-assigned UUID. Primary key. */
  accountId: string;
  /** Device-scoped password generated by the server on POST /v1/account (~50 chars). */
  devicePassword: string;
  /** UUID we generated and sent as X-Device-ID at registration. */
  ownDeviceId: string;
  /** User-supplied label shown to other devices (e.g. "Firefox @ Desktop"). */
  deviceLabel: string;
  /** Sync server endpoint. Reconstructed URL = `${protocol}://${domain}:${port}`. */
  serverAddress: {
    domain: string;
    protocol: "http" | "https";
    port: number;
  };
  /**
   * Tink proto keyset bytes (typically ~70 bytes) — the AES-GCM-SIV key shared
   * across all devices on the account. M2 will replace the placeholder with real
   * parse/serialize against Tink's wire format.
   */
  encryptionKeyset: Uint8Array;
  /** When this record was created locally (epoch ms). */
  createdAt: number;
}

interface OctiWebDB extends DBSchema {
  credentials: {
    key: string; // accountId
    value: CredentialRecord;
  };
}

/**
 * Channel-scoped storage keys. Canary and stable share the same origin
 * ({@code web.octi.darken.eu}) and therefore the same IndexedDB / localStorage,
 * so the channel suffix isolates them: a schema upgrade on canary can't open
 * the DB at a higher version than stable code is prepared to handle. Channels
 * are independent devices on the sync account; pairing both gives the user two
 * device records on the same account.
 *
 * Pre-channel-suffix builds used the unsuffixed {@code "octi-web"} DB. New
 * builds (stable or canary) never touch the legacy DB — users who linked
 * before channels existed retain their old data only as long as they keep
 * running the pre-canary build.
 */
const DB_NAME = `octi-web-${OCTI_WEB_CHANNEL}`;
const DB_VERSION = 1;
const STORE = "credentials";
const ACTIVE_ACCOUNT_KEY = `octi-web.${OCTI_WEB_CHANNEL}.active-account-id`;

let dbPromise: Promise<IDBPDatabase<OctiWebDB>> | null = null;

function getDb(): Promise<IDBPDatabase<OctiWebDB>> {
  if (!dbPromise) {
    dbPromise = openDB<OctiWebDB>(DB_NAME, DB_VERSION, {
      upgrade(db, oldVersion) {
        // v0 → v1: create the credentials store. Future versions add to this switch.
        if (oldVersion < 1) {
          db.createObjectStore(STORE, { keyPath: "accountId" });
        }
      },
    });
  }
  return dbPromise;
}

export class CredentialsRepo {
  async save(record: CredentialRecord): Promise<void> {
    const db = await getDb();
    await db.put(STORE, record);
    localStorage.setItem(ACTIVE_ACCOUNT_KEY, record.accountId);
  }

  async getActive(): Promise<CredentialRecord | undefined> {
    const accountId = localStorage.getItem(ACTIVE_ACCOUNT_KEY);
    if (!accountId) return undefined;
    const db = await getDb();
    const record = await db.get(STORE, accountId);
    if (!record) {
      // Pointer is stale (record was deleted out-of-band). Clean it up.
      localStorage.removeItem(ACTIVE_ACCOUNT_KEY);
    }
    return record;
  }

  async listAll(): Promise<CredentialRecord[]> {
    const db = await getDb();
    return db.getAll(STORE);
  }

  async clearActive(): Promise<void> {
    const accountId = localStorage.getItem(ACTIVE_ACCOUNT_KEY);
    if (!accountId) return;
    const db = await getDb();
    await db.delete(STORE, accountId);
    localStorage.removeItem(ACTIVE_ACCOUNT_KEY);
  }

  /** Hard reset — wipes the whole DB. Used by Settings "sign out from this device". */
  async wipe(): Promise<void> {
    const db = await getDb();
    await db.clear(STORE);
    localStorage.removeItem(ACTIVE_ACCOUNT_KEY);
  }
}

export const credentialsRepo = new CredentialsRepo();
